const menu = [
    {
        id: 1,
        title: "pasta salad",
        category: "starters",
        img: "./images/pasta-salad.jpg",
        desc: `Pasta salad with smoked chicken and crunchy vegetables.`,
    },

    {
        id: 2,
        title: "BBQ Chicken",
        category: "main course",
        img: "./images/bbq-chicken.jpg",
        desc: `BBQ chicken drumsticks and thighs.   `,
    },
    {
        id: 3,
        title: "catfish pepper soup",
        category: "nigerian dishes",
        img: "./images/catfish.jpg",
        // desc: `ombucha chillwave fanny pack 3 wolf moon street art photo booth before they sold out organic viral.`,
    },
    // {
    //   id: 4,
    //   title: "buttermilk pancakes",
    //   category: "starters",
    //   img: "./images/item-1.jpeg",
    //   desc: `I'm baby woke mlkshk wolf bitters live-edge blue bottle, hammock freegan copper mug whatever cold-pressed `,
    // },
    {
        id: 5,
        title: "steak",
        category: "main course",
        // img: "./images/steak.jpg",
        desc: `Cracked pepper rib steaks.       `,
    },
    {
        id: 6,
        title: "afang soup",
        category: "nigerian dishes",
        // img: "./images/afang-soup.jpg",
        // desc: `Portland chicharrones ethical edison bulb, palo santo craft beer chia heirloom iPhone everyday`,
    },
    {
        id: 7,
        title: "smoked chicken chili",
        category: "starters",
        // img: "./images/smoked-chicken-chili.jpg",
        desc: `Smoked Chicken, chili and green bean salad with wild African honey-mustard `,
    },

    {
        id: 8,
        title: "grilled fish",
        category: "main course",
        // img: "./images/grilled-fish.jpg",
        desc: `Grilled fish fillet with tomato salsa.  `,
    },
    {
        id: 9,
        title: "spaghetti",
        category: "main course",
        // img: "./images/spaghetti.jpg",
        desc: `Stir fried spaghetti with chicken.`,
    },
    {
        id: 10,
        title: "prawns",
        category: "starters",
        // img: "./images/prawns.jpg",
        desc: `Prawns tossed with Cucumbers, and light curry dressing. 
        `,
    },
    {
        id: 11,
        title: "Potatoes",
        category: "starters",
        // img: "./images/potato-salmon.jpg",
        desc: `Potatoes with roasted  Norwegian salmon chives.`,
    },
    {
        id: 12,
        title: "bread",
        category: "starters",
        // img: "./images/bread.jpg",
        desc: `Homemade deli style infused breads. `,
    },
    {
        id: 13,
        title: "seafood curry",
        category: "main course",
        // img: "./images/seafood-curry.jpg",
        desc: `Seafood curry sauce .`,
    },
    {
        id: 14,
        title: "spicy rice",
        category: "main course",
        // img: "./images/spicy-rice.jpg",
        desc: `Egg fried spicy rice with wok fried green vegetables.`,
    },
    {
        id: 15,
        title: "char grilled fish",
        category: "main course",
        // img: "./images/char-grilled-fish.jpg",
        desc: `Char grilled fish with tomato chunks and lemon.`,
    },
    {
        id: 16,
        title: "turkey stew",
        category: "nigerian dishes",
        // img: "./images/turkey-stew.jpg",
        // desc: `Portland chicharrones ethical edison bulb, palo santo craft beer chia heirloom iPhone everyday`,
    },
    {
        id: 17,
        title: "grilled chicken suya",
        category: "nigerian dishes",
        // img: "./images/chicken-suya.jpg",
        // desc: `Portland chicharrones ethical edison bulb, palo santo craft beer chia heirloom iPhone everyday`,
    },
    {
        id: 18,
        title: "fried rice & jollof rice",
        category: "nigerian dishes",
        // img: "./images/fried-jollof.jpg",
        // desc: `Portland chicharrones ethical edison bulb, palo santo craft beer chia heirloom iPhone everyday`,
    },
    {
        id: 19,
        title: "egusi soup",
        category: "nigerian dishes",
        // img: "./images/egusi.jpg",
        // desc: `Portland chicharrones ethical edison bulb, palo santo craft beer chia heirloom iPhone everyday`,
    },
    {
        id: 20,
        title: "Semovita & poundo",
        category: "nigerian dishes",
        // img: "./images/semo-poundo.jpg",
        // desc: `Portland chicharrones ethical edison bulb, palo santo craft beer chia heirloom iPhone everyday`,
    },
    {
        id: 21,
        title: "moi moi & plantain",
        category: "nigerian dishes",
        // img: "./images/moi-plantain.jpg",
        // desc: `Portland chicharrones ethical edison bulb, palo santo craft beer chia heirloom iPhone everyday`,
    },
    {
        id: 22,
        title: "cocktails",
        category: "drinks",
        // img: './images/cocktails.jpg',
        // desc: `Mojito, Swimming pool, Whisky sour, Capriha, Pina Colada`,
        types: {
            num1: "Mojito",
            num2: "Swimming pool",
            num3: "Whisky sour",
            num4: "Capriha",
            num5: "Pina Colada",
        }
    },
    {
        id: 23,
        title: "mocktails",
        category: "drinks",
        // img: './images/mocktails.jpg',
        // desc: `Virgin Colada, Nojito-Strawberry, Nojito-Green Apple, Chapman`,
        types: {
            num1: "Virgin Colada",
            num2: "Nojito-Strawberry",
            num3: "Nojito-Green Apple",
            num4: "Chapman"
        }
    },
];
export default menu;
